# Optional: ArgoCD Project definition for better access control
# This can be applied separately if you want to restrict access
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  description: Default project for EdgeShop applications
  sourceRepos:
    - '*'  # Allow all repositories (restrict in production)
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
